### ISSUE TITLE
--script

### ISSUE THREAD

**Issue by Br3wCe** [SpoddyCoder/clonepi#1]
In the description of the --script option is the comment TODO: 

Is this option usable or means the TODO that this is coming in a later version?

**Comment by SpoddyCoder** [comment]
Hi - very late reply - but as they say - better late than never! 

Yes the TODO highlight's it's status. I'm doing some more work on clonepi this week - this feature will be coming soon :)

**Comment by SpoddyCoder** [comment]
Hi @Br3wCe  ...the --script feature is now released. Please see the README for tips about using it.
