### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by talyne67** [SpoddyCoder/clonepi#3]
Hello
I tried to install clonepi but it seems that  there is a  version conflict in the script .
the install script check the version (latest 1.7.3) but  the head of the script is 1.6.2.
Installation error message :

xargs: echo: No such file or directory
Welcome to the ClonePi installer
xargs: echo: No such file or directory
Checking for latest version number at GitHub...
...latest available version is 1.7.3
ERROR: Source install dir is not upto date.
Download the latest zip to get latest version.
Aborting!

configuration:
RPI3  /  NOOB with  2 environments : debian stretch and kodi
download zip on a PC and copy files in /pi  via kodi ssh connection .

tried to install the same files directly on debian environment with a keyboard connected to the RPI
same errors above  without the "xargs"  errors.

thanks

**Comment by SpoddyCoder** [comment]
Hi @talyne67

The `last updated @ v1.6.2` header in the installer is not the same as the latest version of clonepi, which is 1.7.3. You should be able to see `VER=1.7.3` in `/src/clonepi`

Some questions;

1) Is this a fresh install of clonepi or an upgrade?
2) Can you confirm you downloaded the source zip? (you didn't clone the repo)
3) Are you running the installer when inside the clonepi directory? eg...

```
cd /where/i/put/the/zip/clonepi/
sudo ./install.sh
```

**Comment by talyne67** [comment]
1.fresh install
2.zip downloaded on a PC.  De-zip here in a   /clonepi/ directory .  Upload files to the RPI by ssh.
3. yes, in the /clonepi/ directory, two methods  , by ssh from the PC and directly on the RPI with a keyboard and TV connected.

**Comment by SpoddyCoder** [comment]
Should be fine doing everything over SSH - no need to attach the keyboard.

Are you running the install on the debian environment, when the debian environment is running? <-- should be yes to both of those questions - as I think Kodi is a very stripped down install and likely missing some of the tools clonepi uses (I'll update the installer to check for these missing deps if this is found to be the case).

The error message is a touch cryptic - I'll need to setup a test case. While I do that, can you confirm you've got these basic commands available when shelled into the pi...

```
cut --version
xargs --version
```

And let me know the versions of both, thanks.

**Comment by talyne67** [comment]
![capture d ecran de 2018-12-22 11-34-25](https://user-images.githubusercontent.com/45998182/50373324-a83d1f00-05dd-11e9-87f1-46a384ddaee0.png)
As you can see in screeshot above,  I set up ssh connection in rasbian environnement (previously I was connected in ssh kodi environment) .
So, debian is running, tried to install in clonepi dir. Same error.
You can see the cut and xargs versions

**Comment by SpoddyCoder** [comment]
Thanks for posting the screenshot - looks like you're doing everything correct. I'll setup test case in the next day or so and come back.

**Comment by PushEngineering** [comment]
Think I've just squished this one - still cannot recreate / explain the xargs echo error - but there was a silly bug in the installer when using the download zip rather than cloning the repo.

v1.7.4 is now up - hopefully should see you good :) Would appreciate if you can confirm back if it resolved your issue, thanks.

**Comment by talyne67** [comment]
Installation process done. Thanks

**Comment by SpoddyCoder** [comment]
Cool - thanks for reporting the issue and confirming resolved.
