### ISSUE TITLE
Error: Could not stat device /dev/mmcblk0

### ISSUE THREAD

**Issue by timdonovanuk** [SpoddyCoder/clonepi#5]
Trying to run on a Pi3+ to clone onto another USB stick.
```
pi@raspberrypi:~ $ sudo clonepi /dev/sdb --init-destination

Error: Could not stat device /dev/mmcblk0 - No such file or directory.
fdisk: cannot open /dev/mmcblk0: No such file or directory
/usr/local/sbin/clonepi: line 648: [: !=: unary operator expected
Error: Could not stat device /dev/mmcblk0 - No such file or directory.
Error: Could not stat device /dev/mmcblk0 - No such file or directory.
Pre-flight checks completed OK
Info: the following actions will be taken...
Info: 1) destinaton disk /dev/sdb will be initialised to match the source disk structure
Info: 2) destination disk partitions will be mounted inside /mnt/clone/:
Info:    /dev/sdb
Info: 3) filesystems will be synced:
Info:      -->  /mnt/clone/sdb
Info: 4) cleanup source + destination mounts & dirs

Do you wish to continue (yes|no)? yes
User confirmed, starting clone process : 2019-02-18T14:41:47
Error: Could not stat device /dev/mmcblk0 - No such file or directory.
Error: Could not stat device /dev/mmcblk0 - No such file or directory.
Info: initialising /dev/sdb, this may take some time...
Info: setting up destination partition structure, copying 1MB...
dd: failed to open '/dev/mmcblk0': No such file or directory
Error: /dev/sdb partial image did not complete.
Aborting!
```

**Comment by timdonovanuk** [comment]
So I think this entire application assumes you've booted the Pi from an SD card..The ability to boot from USB has been an option for years.

**Comment by SpoddyCoder** [comment]
It's true that it's only been tested using SD card - but it should be easily possible to tweak the config to specify different source drive identifier, you may need to edit `/etc/clonepi/clonepi.conf` to make it work with your system setup...

https://github.com/SpoddyCoder/clonepi#config-files

Can you run the following command & paste the output and I can help you determine the tweak you need to make...

```
sudo fdisk -l
```

**Comment by timdonovanuk** [comment]
Thanks! I've uploaded this to https://gist.github.com/timdonovanuk/9945d8cbdfa454a3ca695f6e7bdd10f6

In the mean time though, I've just used billw2/rpi-clone as this seems to do everything I need.

Cheers.

**Comment by timdonovanuk** [comment]
Ok, I see in the conf there is SRC_DISK="/dev/mmcblk0". This perhaps needs reworking or at least removing as a default, since Pi's now boot off all sorts of devices (SSD's, USB, network etc.). Thanks 👍
