### ISSUE TITLE
If I backup my Pi to a file, how do I restore it to a SD?

### ISSUE THREAD

**Issue by crankynet** [SpoddyCoder/clonepi#9]
Is the saved file an image of the ID and I can use Win32diskimage or something like that under WIndows to write to a SD card?

**Comment by SpoddyCoder** [comment]
Yep all correct :) The resulting file is a disk image - win32diskimage is able to write these image files to a new SD card...

https://www.raspberrypi.org/documentation/installation/installing-images/windows.md

**Comment by CaptainMidnight** [comment]
Hi just a simple question, is clonepi still being maintained and rpi-clone base of the code, is that inline with the latest available version of rpi-clone?

Much prefer being able to create an image file, but just wondering about the support availability and date of the code.
